import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Replon App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={`${inter.className} bg-slate-200`}>
      <main className="flex h-dvh flex-col items-center justify-between px-5 py-4 bg-white md:max-w-[640px] md:mx-auto">
        {children}
        <Toaster position="bottom-center" richColors />
        <SpeedInsights />
      </main>
      </body>
    </html>
  );
}
